pipeline {
  agent any

  parameters {
    choice(
      name: 'ACTION',
      choices: ['Deploy', 'Destroy'],
      description: 'Deploy the app, or destroy all AWS infrastructure'
    )
  }

  environment {
    AWS_REGION = 'ap-southeast-1'
    // No credentials block needed — ECR URL is derived from Terraform output,
    // DB passwords are generated by Terraform and stored in AWS Secrets Manager,
    // AWS access comes from the EC2 instance role on the Jenkins server.

    // pip --user installs land in the Jenkins home .local/bin
    PATH = "/var/lib/jenkins/.local/bin:/usr/local/bin:/usr/bin:/bin:${env.PATH}"
  }

  stages {

    stage('Checkout') {
      steps {
        // checkout scm uses whatever repo is configured in the Jenkins job —
        // works for the original repo and any fork without changing this file.
        checkout scm
      }
    }

    // ── DEPLOY ─────────────────────────────────────────────────────────────

    stage('Provision Infra') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        // Terraform generates passwords internally (random_password resource).
        // No variables, no secrets, no credentials needed here.
        sh '''
          set -e
          cd terraform
          terraform init -input=false
          terraform apply -auto-approve -input=false
        '''
      }
    }

    stage('Update kubeconfig') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        sh 'aws eks update-kubeconfig --name event-app-cluster --region $AWS_REGION'
      }
    }

    stage('Update kubeconfig for Destroy') {
      when { expression { params.ACTION == 'Destroy' } }
      steps {
        sh '''
          aws eks update-kubeconfig --name event-app-cluster --region $AWS_REGION \
            || echo "Cluster already destroyed — skipping kubeconfig update"
        '''
      }
    }

    stage('Fetch Terraform outputs') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        script {
          env.ECR_REPO = sh(
            script: 'cd terraform && terraform output -raw ecr_repo_url',
            returnStdout: true
          ).trim()
          env.AWS_SECRET_NAME = sh(
            script: 'cd terraform && terraform output -raw db_secret_name',
            returnStdout: true
          ).trim()
          env.ESO_ROLE_ARN = sh(
            script: 'cd terraform && terraform output -raw eso_role_arn',
            returnStdout: true
          ).trim()
          echo "ECR repo:      ${env.ECR_REPO}"
          echo "DB secret:     ${env.AWS_SECRET_NAME}"
          echo "ESO role ARN:  ${env.ESO_ROLE_ARN}"
        }
      }
    }

    stage('Deploy via Ansible') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        sh '''
          set -e
          cd ansible
          ansible-playbook -i inventory.ini deploy.yml \
            -e ecr_repo_url=$ECR_REPO \
            -e build_number=$BUILD_NUMBER \
            -e aws_secret_name=$AWS_SECRET_NAME \
            -e aws_region=$AWS_REGION \
            -e eso_role_arn=$ESO_ROLE_ARN
        '''
      }
    }

    stage('Wait for LoadBalancer & Verify') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        script {
          def dns = ''
          timeout(time: 5, unit: 'MINUTES') {
            waitUntil {
              dns = sh(
                script: "kubectl get svc tomcat-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true",
                returnStdout: true
              ).trim()
              if (dns) { return true }
              echo 'Waiting for ELB DNS...'
              sleep(time: 15, unit: 'SECONDS')
              return false
            }
          }
          env.APP_URL = "http://${dns}"

          timeout(time: 3, unit: 'MINUTES') {
            waitUntil {
              def code = sh(
                script: "curl -s -o /dev/null -w '%{http_code}' ${env.APP_URL} || true",
                returnStdout: true
              ).trim()
              if (code == '200') { return true }
              echo "HTTP ${code} — waiting..."
              sleep(time: 15, unit: 'SECONDS')
              return false
            }
          }

          echo "=================================================="
          echo " App is live at: ${env.APP_URL}"
          echo "=================================================="
        }
        sh 'kubectl get pods -o wide'
      }
    }

    // ── DESTROY ────────────────────────────────────────────────────────────

    stage('Remove LoadBalancer Service') {
      when { expression { params.ACTION == 'Destroy' } }
      steps {
        // Delete the ELB before destroying the cluster — otherwise the ELB
        // becomes orphaned and keeps charging money.
        sh 'kubectl delete svc tomcat-service --ignore-not-found=true'
      }
    }

    stage('Destroy Infra') {
      when { expression { params.ACTION == 'Destroy' } }
      steps {
        sh '''
          cd terraform
          terraform init -input=false
          terraform destroy -auto-approve -input=false
        '''
      }
    }
  }

  post {
    success {
      script {
        if (params.ACTION == 'Deploy' && env.APP_URL) {
          echo "Deploy complete — ${env.APP_URL}"
        } else {
          echo "${params.ACTION} completed successfully."
        }
      }
    }
    failure {
      echo "Pipeline failed during ${params.ACTION} — check stage logs above."
    }
  }
}
