pipeline {
  agent any

  parameters {
    choice(
      name: 'ACTION',
      choices: ['Deploy', 'Destroy'],
      description: 'Deploy the app, or destroy all AWS infrastructure'
    )
  }

  environment {
    AWS_REGION = 'ap-southeast-1'
    // No credentials block needed — ECR URL is derived from Terraform output,
    // DB passwords are generated by Terraform and stored in AWS Secrets Manager,
    // AWS access comes from the EC2 instance role on the Jenkins server.

    // Jenkins runs shell steps with a minimal PATH — explicitly add the locations
    // where pip (system-wide) and package managers install CLI tools.
    PATH = "/usr/local/bin:/usr/bin:/bin:${env.PATH}"
  }

  stages {

    stage('Checkout') {
      steps {
        // checkout scm uses whatever repo is configured in the Jenkins job —
        // works for the original repo and any fork without changing this file.
        checkout scm
      }
    }

    // ── DEPLOY ─────────────────────────────────────────────────────────────

    stage('Security Scan - Configs') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        // Trivy config scan — checks Terraform files and Kubernetes manifests
        // for misconfigurations (open ports, missing resource limits, etc.).
        // exit-code 0 means the stage reports findings but does NOT fail the
        // build — use this to review and fix issues incrementally.
        sh '''
          echo "=== Scanning Terraform configs ==="
          trivy config --exit-code 0 --severity HIGH,CRITICAL terraform/

          echo "=== Scanning Kubernetes manifests ==="
          trivy config --exit-code 0 --severity HIGH,CRITICAL ansible/templates/

          echo "=== Scanning Dockerfile ==="
          trivy config --exit-code 0 --severity HIGH,CRITICAL app/Dockerfile
        '''
      }
    }

    stage('Provision Infra') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        // Terraform generates passwords internally (random_password resource).
        // No variables, no secrets, no credentials needed here.
        sh '''
          set -e
          cd terraform
          terraform init -input=false
          terraform apply -auto-approve -input=false
        '''
      }
    }

    stage('Update kubeconfig') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        sh 'aws eks update-kubeconfig --name event-app-cluster --region $AWS_REGION'
      }
    }

    stage('Update kubeconfig for Destroy') {
      when { expression { params.ACTION == 'Destroy' } }
      steps {
        sh '''
          aws eks update-kubeconfig --name event-app-cluster --region $AWS_REGION \
            || echo "Cluster already destroyed — skipping kubeconfig update"
        '''
      }
    }

    stage('Fetch Terraform outputs') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        script {
          env.ECR_REPO = sh(
            script: 'cd terraform && terraform output -raw ecr_repo_url',
            returnStdout: true
          ).trim()
          env.AWS_SECRET_NAME = sh(
            script: 'cd terraform && terraform output -raw db_secret_name',
            returnStdout: true
          ).trim()
          env.ESO_ROLE_ARN = sh(
            script: 'cd terraform && terraform output -raw eso_role_arn',
            returnStdout: true
          ).trim()
          echo "ECR repo:      ${env.ECR_REPO}"
          echo "DB secret:     ${env.AWS_SECRET_NAME}"
          echo "ESO role ARN:  ${env.ESO_ROLE_ARN}"
        }
      }
    }

    stage('Build & Scan Image') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        sh '''
          set -e

          # Log in to ECR so docker can push to it
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $ECR_REPO

          # Build the Docker image
          docker build -t $ECR_REPO:$BUILD_NUMBER ./app

          echo "=== Trivy image scan — HIGH findings (informational) ==="
          trivy image --exit-code 0 --severity HIGH $ECR_REPO:$BUILD_NUMBER

          echo "=== Trivy image scan — CRITICAL findings (build gate) ==="
          # exit-code 1 fails the pipeline if any CRITICAL CVE is found.
          # Fix: update the base image in app/Dockerfile or suppress a known
          # false-positive with a .trivyignore file at the repo root.
          trivy image --exit-code 1 --severity CRITICAL $ECR_REPO:$BUILD_NUMBER

          # Push only after the scan passes
          docker push $ECR_REPO:$BUILD_NUMBER
        '''
      }
    }

    stage('Deploy via Ansible') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        // Image is already built and pushed by the previous stage.
        // Ansible handles ESO installation and Kubernetes deployment only.
        sh '''
          set -e
          cd ansible
          ansible-playbook -i inventory.ini deploy.yml \
            -e ecr_repo_url=$ECR_REPO \
            -e build_number=$BUILD_NUMBER \
            -e aws_secret_name=$AWS_SECRET_NAME \
            -e aws_region=$AWS_REGION \
            -e eso_role_arn=$ESO_ROLE_ARN
        '''
      }
    }

    stage('Wait for LoadBalancer & Verify') {
      when { expression { params.ACTION == 'Deploy' } }
      steps {
        script {
          def dns = ''
          timeout(time: 5, unit: 'MINUTES') {
            waitUntil {
              dns = sh(
                script: "kubectl get svc tomcat-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true",
                returnStdout: true
              ).trim()
              if (dns) { return true }
              echo 'Waiting for ELB DNS...'
              sleep(time: 15, unit: 'SECONDS')
              return false
            }
          }
          env.APP_URL = "http://${dns}"

          timeout(time: 3, unit: 'MINUTES') {
            waitUntil {
              def code = sh(
                script: "curl -s -o /dev/null -w '%{http_code}' ${env.APP_URL} || true",
                returnStdout: true
              ).trim()
              if (code == '200') { return true }
              echo "HTTP ${code} — waiting..."
              sleep(time: 15, unit: 'SECONDS')
              return false
            }
          }

          echo "=================================================="
          echo " App is live at: ${env.APP_URL}"
          echo "=================================================="
        }
        sh 'kubectl get pods -o wide'
      }
    }

    // ── DESTROY ────────────────────────────────────────────────────────────

    stage('Remove LoadBalancer Service') {
      when { expression { params.ACTION == 'Destroy' } }
      steps {
        // Delete the ELB before destroying the cluster — otherwise the ELB
        // becomes orphaned and keeps charging money.
        sh 'kubectl delete svc tomcat-service --ignore-not-found=true'
      }
    }

    stage('Remove EBS Volumes') {
      when { expression { params.ACTION == 'Destroy' } }
      steps {
        sh '''
          # Step 1 — Delete the StatefulSet so the MySQL pod stops and
          # unmounts the EBS volume. Deleting a PVC while a pod still
          # has the volume mounted forces Kubernetes to wait for the pod
          # to terminate before it can detach and delete the volume —
          # which is why it hangs. Stopping the pod first avoids that wait.
          kubectl delete statefulset mysql --ignore-not-found=true

          # Step 2 — Wait for the MySQL pod to fully terminate.
          # Once the pod is gone the volume is detached and the PVC
          # deletion will complete almost instantly.
          kubectl wait --for=delete pod/mysql-0 --timeout=60s || true

          # Step 3 — Now delete all PVCs. Volume is already detached
          # so this completes in seconds rather than minutes.
          kubectl delete pvc --all --all-namespaces --ignore-not-found=true
          kubectl wait --for=delete pvc --all --all-namespaces --timeout=60s || true
        '''
      }
    }

    stage('Destroy Infra') {
      when { expression { params.ACTION == 'Destroy' } }
      steps {
        sh '''
          cd terraform
          terraform init -input=false
          terraform destroy -auto-approve -input=false
        '''
      }
    }
  }

  post {
    success {
      script {
        if (params.ACTION == 'Deploy' && env.APP_URL) {
          echo "Deploy complete — ${env.APP_URL}"
        } else {
          echo "${params.ACTION} completed successfully."
        }
      }
    }
    failure {
      echo "Pipeline failed during ${params.ACTION} — check stage logs above."
    }
  }
}
