# ---------------------------------------------------------------------------
# Passwords — auto-generated by Terraform, never set by a human
#
# No TF_VAR_* variables, no Jenkins credentials, no manual rotation.
# Terraform owns the full lifecycle: generate → store → rotate.
# ---------------------------------------------------------------------------

resource "random_password" "mysql_app" {
  length           = 24
  special          = true
  override_special = "!#%^&*"   # exclude chars that break JDBC URLs
}

resource "random_password" "mysql_root" {
  length           = 24
  special          = true
  override_special = "!#%^&*"
}

# ---------------------------------------------------------------------------
# AWS Secrets Manager — single source of truth for all DB credentials
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = "event-app/db-credentials"
  description             = "MySQL credentials for the event-registration app (Terraform-managed)"
  recovery_window_in_days = 0   # instant delete on `terraform destroy` — fine for demo

  tags = {
    Project     = "event-registration-app"
    ManagedBy   = "terraform"
  }
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id

  secret_string = jsonencode({
    DB_URL              = "jdbc:mysql://mysql-service:3306/eventdb"
    DB_USER             = "eventuser"
    DB_PASS             = random_password.mysql_app.result
    MYSQL_ROOT_PASSWORD = random_password.mysql_root.result
    MYSQL_DATABASE      = "eventdb"
    MYSQL_USER          = "eventuser"
    MYSQL_PASSWORD      = random_password.mysql_app.result
  })
}

# ---------------------------------------------------------------------------
# IRSA — IAM Role for Service Account (External Secrets Operator)
#
# Scoped to the ESO service account only — no other pod on the cluster
# can assume this role or read the DB credentials secret.
# This replaces the old node-level IAM policy (which granted access to
# every pod on every node — a security anti-pattern).
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "eso_assume_role" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    effect  = "Allow"

    principals {
      type        = "Federated"
      identifiers = [module.eks.oidc_provider_arn]
    }

    # Trust only the ESO service account in the external-secrets namespace
    condition {
      test     = "StringEquals"
      variable = "${module.eks.oidc_provider}:sub"
      values   = ["system:serviceaccount:external-secrets:external-secrets"]
    }

    condition {
      test     = "StringEquals"
      variable = "${module.eks.oidc_provider}:aud"
      values   = ["sts.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "eso" {
  name               = "event-app-eso-irsa"
  assume_role_policy = data.aws_iam_policy_document.eso_assume_role.json
  description        = "IRSA role for External Secrets Operator - read-only on db-credentials secret"
}

data "aws_iam_policy_document" "eso_read_secret" {
  statement {
    sid    = "AllowESOReadDbSecret"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:DescribeSecret",
    ]
    resources = [aws_secretsmanager_secret.db_credentials.arn]
  }
}

resource "aws_iam_policy" "eso_read_secret" {
  name        = "EventAppESOReadSecret"
  description = "Grants ESO read access to the event-app DB credentials secret only"
  policy      = data.aws_iam_policy_document.eso_read_secret.json
}

resource "aws_iam_role_policy_attachment" "eso_read_secret" {
  role       = aws_iam_role.eso.name
  policy_arn = aws_iam_policy.eso_read_secret.arn
}
