variable "aws_region" {
  default = "ap-southeast-1"
}

variable "cluster_name" {
  default = "event-app-cluster"
}

variable "node_instance_type" {
  default = "t3.medium"
}

# DB passwords are intentionally NOT variables here.
# They are generated by Terraform's random_password resource in secrets.tf
# so no human ever sets, sees, or rotates them manually.
